package argparse

// Code generated by ../../bin/structDefaultInit - DO NOT EDIT.
import (
	"github.com/barbell-math/util/src/argparse/translators"
	"github.com/barbell-math/util/src/generics"
)

// Returns a new opts struct initialized with the default values.
func NewOpts[T translators.Translator[U], U any]() *opts[T, U] {
	return &opts[T, U]{
		argType:               ValueArgType,
		shortName:             byte(0),
		required:              false,
		conditionallyRequired: []ArgConditionality[U]{},
		description:           "",
		defaultVal:            generics.ZeroVal[U](),
		defaultValProvided:    false,
		translator:            generics.ZeroVal[T](),
	}
}

// The type of argument. This value will affect how the parser expects
// values, so make sure it is the right value. See [ArgType] for
// descriptions of available types.
//
//gen:structDefaultInit default ValueArgType
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) SetArgType(v ArgType) *opts[T, U] {
	o.argType = v
	return o
}

// The short name to associate with the argument. These will usually
// follow a form similar to '-t'.
//
//gen:structDefaultInit default byte(0)
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) SetShortName(v byte) *opts[T, U] {
	o.shortName = v
	return o
}

// Defines if the argument is required or not.
//
//gen:structDefaultInit default false
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) SetRequired(v bool) *opts[T, U] {
	o.required = v
	return o
}

// The list of arguments that must also be provided if this argument is
// provided. All arguments provided are expected to be long names.
//
//gen:structDefaultInit default []ArgConditionality[U]{}
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) SetConditionallyRequired(v []ArgConditionality[U]) *opts[T, U] {
	o.conditionallyRequired = v
	return o
}

// Sets the description that will be printed out on the help menu.
//
//gen:structDefaultInit default ""
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) SetDescription(v string) *opts[T, U] {
	o.description = v
	return o
}

// The translator value to use when parsing the cmd line argument's
// value. Most translators are stateless, but some have state and hence
// must be able to have there value explicitly set.
//
//gen:structDefaultInit default generics.ZeroVal[T]()
//gen:structDefaultInit setter
//gen:structDefaultInit getter
//gen:structDefaultInit imports github.com/barbell-math/util/src/generics github.com/barbell-math/util/src/argparse/translators
func (o *opts[T, U]) SetTranslator(v T) *opts[T, U] {
	o.translator = v
	return o
}

// The type of argument. This value will affect how the parser expects
// values, so make sure it is the right value. See [ArgType] for
// descriptions of available types.
//
//gen:structDefaultInit default ValueArgType
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) GetArgType() ArgType {
	return o.argType
}

// The short name to associate with the argument. These will usually
// follow a form similar to '-t'.
//
//gen:structDefaultInit default byte(0)
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) GetShortName() byte {
	return o.shortName
}

// Defines if the argument is required or not.
//
//gen:structDefaultInit default false
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) GetRequired() bool {
	return o.required
}

// The list of arguments that must also be provided if this argument is
// provided. All arguments provided are expected to be long names.
//
//gen:structDefaultInit default []ArgConditionality[U]{}
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) GetConditionallyRequired() []ArgConditionality[U] {
	return o.conditionallyRequired
}

// Sets the description that will be printed out on the help menu.
//
//gen:structDefaultInit default ""
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *opts[T, U]) GetDescription() string {
	return o.description
}

// The default value that should be used if the argument is not supplied.
// The default defaults to a zero-value initialized value.
//
//gen:structDefaultInit default generics.ZeroVal[U]()
//gen:structDefaultInit getter
//gen:structDefaultInit imports github.com/barbell-math/util/src/generics
func (o *opts[T, U]) GetDefaultVal() U {
	return o.defaultVal
}

// The translator value to use when parsing the cmd line argument's
// value. Most translators are stateless, but some have state and hence
// must be able to have there value explicitly set.
//
//gen:structDefaultInit default generics.ZeroVal[T]()
//gen:structDefaultInit setter
//gen:structDefaultInit getter
//gen:structDefaultInit imports github.com/barbell-math/util/src/generics github.com/barbell-math/util/src/argparse/translators
func (o *opts[T, U]) GetTranslator() T {
	return o.translator
}
