package argparse

// Code generated by ../../bin/structBaseWidget - DO NOT EDIT.

import (
	"github.com/barbell-math/util/src/hash"
	"github.com/barbell-math/util/src/widgets"
)

// Returns true if l equals r using the widgets associated with the following
// fields:
//   - value
//   - _type
func (_ *token) Eq(l *token, r *token) bool {
	var (
		valueWidget widgets.BuiltinString
		_typeWidget *tokenType
		rv          bool = true
	)

	rv = rv && valueWidget.Eq(&l.value, &r.value)
	rv = rv && _typeWidget.Eq(&l._type, &r._type)
	return rv
}

// Returns a hash that represents other by calling [hash.CombineIgnoreZero] with
// the values generated from using the widgets associated with the following
// fields:
//   - value
//   - _type
func (_ *token) Hash(other *token) hash.Hash {
	var (
		valueWidget widgets.BuiltinString
		_typeWidget *tokenType
		rv          hash.Hash
	)

	rv = rv.CombineIgnoreZero(valueWidget.Hash(&other.value))
	rv = rv.CombineIgnoreZero(_typeWidget.Hash(&other._type))
	return rv
}

// Zeros the following fields in the struct using the widgets associated with
// the following fields:
//   - value
//   - _type
func (_ *token) Zero(other *token) {
	var (
		valueWidget widgets.BuiltinString
		_typeWidget *tokenType
	)

	valueWidget.Zero(&other.value)
	_typeWidget.Zero(&other._type)
}
