matrix:
- name: golang
  sources:
  - '**/*.go'
  filters:
  - pyspelling.filters.cpp:
      comments: true
      strings: true
      directives: true

- name: markdown
  sources:
  - '**/*.md'
  filters:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
