package testenum

// Code generated by ../../../bin/enum - DO NOT EDIT.
import (
	"errors"
	"fmt"
)

var (
	InvalidTestEnum            = errors.New("Invalid TestEnum")
	TEST_ENUM       []TestEnum = []TestEnum{
		UnknownTestEnum,
		AppActionOne,
		AppActionTwo,
	}
)

func NewTestEnum() TestEnum {
	return UnknownTestEnum
}

func (o TestEnum) Valid() error {
	switch o {

	case UnknownTestEnum:
		return nil

	case AppActionOne:
		return nil

	case AppActionTwo:
		return nil

	default:
		return InvalidTestEnum
	}
}

func (o TestEnum) String() string {
	switch o {
	case UnknownTestEnum:
		return "unknownTestEnum"
	case AppActionOne:
		return "AppActionOne"
	case AppActionTwo:
		return "AppActionTwo"

	default:
		return "unknownTestEnum"
	}
}

func (o TestEnum) MarshalJSON() ([]byte, error) {
	switch o {

	case UnknownTestEnum:
		return []byte("unknownTestEnum"), nil

	case AppActionOne:
		return []byte("AppActionOne"), nil

	case AppActionTwo:
		return []byte("AppActionTwo"), nil

	default:
		return []byte("unknownTestEnum"), InvalidTestEnum
	}
}

func (o *TestEnum) FromString(s string) error {
	switch s {

	case "unknownTestEnum":
		*o = UnknownTestEnum
		return nil

	case "AppActionOne":
		*o = AppActionOne
		return nil

	case "AppActionTwo":
		*o = AppActionTwo
		return nil

	default:
		*o = UnknownTestEnum
		return fmt.Errorf("%w: %s", InvalidTestEnum, s)
	}
}

func (o *TestEnum) UnmarshalJSON(b []byte) error {
	switch string(b) {

	case "unknownTestEnum":
		*o = UnknownTestEnum
		return nil

	case "AppActionOne":
		*o = AppActionOne
		return nil

	case "AppActionTwo":
		*o = AppActionTwo
		return nil

	default:
		*o = UnknownTestEnum
		return fmt.Errorf("%w: %s", InvalidTestEnum, string(b))
	}
}
