package computers

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestAddValueImplementsComputer_int_(t *testing.T) {
	var typeThing Add[int]
	var iFaceThing Computer[int] = typeThing
	_ = iFaceThing
}

func TestAddPntrImplementsComputer_int_(t *testing.T) {
	var typeThing Add[int]
	var iFaceThing Computer[int] = &typeThing
	_ = iFaceThing
}
