package computers

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestDivValueImplementsComputer_int_(t *testing.T) {
	var typeThing Div[int]
	var iFaceThing Computer[int] = typeThing
	_ = iFaceThing
}

func TestDivPntrImplementsComputer_int_(t *testing.T) {
	var typeThing Div[int]
	var iFaceThing Computer[int] = &typeThing
	_ = iFaceThing
}
