package computers

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestMulValueImplementsComputer_int_(t *testing.T) {
	var typeThing Mul[int]
	var iFaceThing Computer[int] = typeThing
	_ = iFaceThing
}

func TestMulPntrImplementsComputer_int_(t *testing.T) {
	var typeThing Mul[int]
	var iFaceThing Computer[int] = &typeThing
	_ = iFaceThing
}
