package computers

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestStopperValueImplementsComputer_int_(t *testing.T) {
	var typeThing Stopper[int]
	var iFaceThing Computer[int] = typeThing
	_ = iFaceThing
}

func TestStopperPntrImplementsComputer_int_(t *testing.T) {
	var typeThing Stopper[int]
	var iFaceThing Computer[int] = &typeThing
	_ = iFaceThing
}
