package computers

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestSubValueImplementsComputer_int_(t *testing.T) {
	var typeThing Sub[int]
	var iFaceThing Computer[int] = typeThing
	_ = iFaceThing
}

func TestSubPntrImplementsComputer_int_(t *testing.T) {
	var typeThing Sub[int]
	var iFaceThing Computer[int] = &typeThing
	_ = iFaceThing
}
