package generatortests

// Code generated by ../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestTestStructValImplsIFaceValueImplementsIFace(t *testing.T) {
	var typeThing TestStructValImplsIFace
	var iFaceThing IFace = typeThing
	_ = iFaceThing
}
