package generatortests

// Code generated by ../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestTestIntValImplsIFaceValueImplementsIFace(t *testing.T) {
	var typeThing TestIntValImplsIFace
	var iFaceThing IFace = typeThing
	_ = iFaceThing
}
