package generatortests

// Code generated by ../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestTestIntBothImplsIFaceValueImplementsIFace(t *testing.T) {
	var typeThing TestIntBothImplsIFace
	var iFaceThing IFace = typeThing
	_ = iFaceThing
}

func TestTestIntBothImplsIFacePntrImplementsIFace(t *testing.T) {
	var typeThing TestIntBothImplsIFace
	var iFaceThing IFace = &typeThing
	_ = iFaceThing
}
