package widgets

// Code generated by ../bin/widgetInterfaceImpl - DO NOT EDIT.

import (
	"github.com/barbell-math/util/hash"
)

var ()

// A widget to represent the built-in int16 type
type (
	BuiltinInt16 struct{}
)

// Returns true if both int16's are equal. Uses the standard == operator internally.
func (_ BuiltinInt16) Eq(l *int16, r *int16) bool {
	return *l == *r
}

// Provides a hash function for the value that it is wrapping.
func (_ BuiltinInt16) Hash(v *int16) hash.Hash {
	return hash.Hash(*v)
}

// Zeros the supplied value.
func (_ BuiltinInt16) Zero(other *int16) {
	*other = (int16)(0)
}

// Returns true if l<r. Uses the standard < operator internally.
func (_ BuiltinInt16) Lt(l *int16, r *int16) bool {
	return *l < *r
}

// Returns the zero value for the int16 type.
func (_ BuiltinInt16) ZeroVal() int16 {
	return int16(0)
}

// Returns the unit value for the int16 type.
func (_ BuiltinInt16) UnitVal() int16 {
	return int16(1)
}

// Negates v, updating the value that v points to.
func (_ BuiltinInt16) Neg(v *int16) {
	*v = -(*v)
}

// Adds l to r, placing the result in the value that res points to.
func (_ BuiltinInt16) Add(res *int16, l *int16, r *int16) {
	*res = *l + *r
}

// Subtracts l to r, placing the result in the value that res points to.
func (_ BuiltinInt16) Sub(res *int16, l *int16, r *int16) {
	*res = *l - *r
}

// Multiplies l to r, placing the result in the value that res points to.
func (_ BuiltinInt16) Mul(res *int16, l *int16, r *int16) {
	*res = *l * *r
}

// Divides l to r, placing the result in the value that res points to.
func (_ BuiltinInt16) Div(res *int16, l *int16, r *int16) {
	*res = *l / *r
}
