package widgets

// Code generated by ../bin/widgetInterfaceImpl - DO NOT EDIT.

import (
	"github.com/barbell-math/util/hash"
)

var ()

// A widget to represent the built-in bool type
type (
	BuiltinBool struct{}
)

// Returns true if both bool's are equal. Uses the standard == operator internally.
func (_ BuiltinBool) Eq(l *bool, r *bool) bool {
	return *l == *r
}

// Provides a hash function for the value that it is wrapping.
func (_ BuiltinBool) Hash(v *bool) hash.Hash {
	if *v {
		return hash.Hash(1)
	}
	return hash.Hash(0)
}

// Zeros the supplied value.
func (_ BuiltinBool) Zero(other *bool) {
	*other = (bool)(false)
}
