package widgets

// Code generated by ../bin/widgetInterfaceImpl - DO NOT EDIT.

import (
	"github.com/barbell-math/util/hash"
)

var ()

// A widget to represent the built-in uint64 type
type (
	BuiltinUint64 struct{}
)

// Returns true if both uint64's are equal. Uses the standard == operator internally.
func (_ BuiltinUint64) Eq(l *uint64, r *uint64) bool {
	return *l == *r
}

// Provides a hash function for the value that it is wrapping.
func (_ BuiltinUint64) Hash(v *uint64) hash.Hash {
	return hash.Hash(*v)
}

// Zeros the supplied value.
func (_ BuiltinUint64) Zero(other *uint64) {
	*other = (uint64)(0)
}

// Returns true if l<r. Uses the standard < operator internally.
func (_ BuiltinUint64) Lt(l *uint64, r *uint64) bool {
	return *l < *r
}

// Returns the zero value for the uint64 type.
func (_ BuiltinUint64) ZeroVal() uint64 {
	return uint64(0)
}

// Returns the unit value for the uint64 type.
func (_ BuiltinUint64) UnitVal() uint64 {
	return uint64(1)
}

// Negates v, updating the value that v points to.
func (_ BuiltinUint64) Neg(v *uint64) {
	*v = -(*v)
}

// Adds l to r, placing the result in the value that res points to.
func (_ BuiltinUint64) Add(res *uint64, l *uint64, r *uint64) {
	*res = *l + *r
}

// Subtracts l to r, placing the result in the value that res points to.
func (_ BuiltinUint64) Sub(res *uint64, l *uint64, r *uint64) {
	*res = *l - *r
}

// Multiplies l to r, placing the result in the value that res points to.
func (_ BuiltinUint64) Mul(res *uint64, l *uint64, r *uint64) {
	*res = *l * *r
}

// Divides l to r, placing the result in the value that res points to.
func (_ BuiltinUint64) Div(res *uint64, l *uint64, r *uint64) {
	*res = *l / *r
}
