package containers

// Code generated by ../../bin/containerInterfaceTests - DO NOT EDIT.
import (
	"github.com/barbell-math/util/src/container/dynamicContainers"
	"github.com/barbell-math/util/src/container/tests"
	"testing"
)

func SyncedHashMapToMapInterfaceFactory(capacity int) dynamicContainers.Map[int, int] {
	v := generateSyncedHashMap(capacity)
	var rv dynamicContainers.Map[int, int] = &v
	return rv
}

func TestSyncedHashMap_DynMapInterfaceSyncableInterface(t *testing.T) {
	tests.DynMapInterfaceSyncableInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceAddressableInterface(t *testing.T) {
	tests.DynMapInterfaceAddressableInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceLengthInterface(t *testing.T) {
	tests.DynMapInterfaceLengthInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceClearInterface(t *testing.T) {
	tests.DynMapInterfaceClearInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceWriteKeyedOpsInterface(t *testing.T) {
	tests.DynMapInterfaceWriteKeyedOpsInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceReadOpsInterface(t *testing.T) {
	tests.DynMapInterfaceReadOpsInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceReadKeyedOpsInterface(t *testing.T) {
	tests.DynMapInterfaceReadKeyedOpsInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceDeleteOpsInterface(t *testing.T) {
	tests.DynMapInterfaceDeleteOpsInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceDeleteKeyedOpsInterface(t *testing.T) {
	tests.DynMapInterfaceDeleteKeyedOpsInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_ReadDynMapInterface(t *testing.T) {
	tests.ReadDynMapInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_WriteDynMapInterface(t *testing.T) {
	tests.WriteDynMapInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceInterface(t *testing.T) {
	tests.DynMapInterfaceInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceStaticCapacityInterface(t *testing.T) {
	tests.DynMapInterfaceStaticCapacityInterface(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceGet(t *testing.T) {
	tests.DynMapInterfaceGet(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceGetPntr(t *testing.T) {
	tests.DynMapInterfaceGetPntr(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceSet(t *testing.T) {
	tests.DynMapInterfaceSet(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceContains(t *testing.T) {
	tests.DynMapInterfaceContains(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceContainsPntr(t *testing.T) {
	tests.DynMapInterfaceContainsPntr(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceKeyOf(t *testing.T) {
	tests.DynMapInterfaceKeyOf(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceKeyOfPntr(t *testing.T) {
	tests.DynMapInterfaceKeyOfPntr(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfacePop(t *testing.T) {
	tests.DynMapInterfacePop(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfacePopPntr(t *testing.T) {
	tests.DynMapInterfacePopPntr(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceDelete(t *testing.T) {
	tests.DynMapInterfaceDelete(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceClear(t *testing.T) {
	tests.DynMapInterfaceClear(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceKeys(t *testing.T) {
	tests.DynMapInterfaceKeys(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceVals(t *testing.T) {
	tests.DynMapInterfaceVals(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_DynMapInterfaceValPntrs(t *testing.T) {
	tests.DynMapInterfaceValPntrs(SyncedHashMapToMapInterfaceFactory, t)
}

func TestSyncedHashMap_HashDynMapInterfaceKeyedEq(t *testing.T) {
	tests.HashDynMapInterfaceKeyedEq(SyncedHashMapToMapInterfaceFactory, t)
}
