package containers

// Code generated by ../../../bin/containerInterfaceTests - DO NOT EDIT.
import (
	"github.com/barbell-math/util/src/container/staticContainers"
	"github.com/barbell-math/util/src/container/tests"
	"testing"
)

func SyncedCircularBufferToSetInterfaceFactory(capacity int) staticContainers.Set[int] {
	v := generateSyncedCircularBuffer(capacity)
	var rv staticContainers.Set[int] = &v
	return rv
}

func TestSyncedCircularBuffer_StaticSetInterfaceStaticCapacity(t *testing.T) {
	tests.StaticSetInterfaceStaticCapacity(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceLengthInterface(t *testing.T) {
	tests.StaticSetInterfaceLengthInterface(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceClearInterface(t *testing.T) {
	tests.StaticSetInterfaceClearInterface(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceWriteUniqueOpsInterface(t *testing.T) {
	tests.StaticSetInterfaceWriteUniqueOpsInterface(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceReadOpsInterface(t *testing.T) {
	tests.StaticSetInterfaceReadOpsInterface(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceDeleteOpsInterface(t *testing.T) {
	tests.StaticSetInterfaceDeleteOpsInterface(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_ReadStaticSetInterface(t *testing.T) {
	tests.ReadStaticSetInterface(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_WriteStaticSetInterface(t *testing.T) {
	tests.WriteStaticSetInterface(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceInterface(t *testing.T) {
	tests.StaticSetInterfaceInterface(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceVals(t *testing.T) {
	tests.StaticSetInterfaceVals(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceValPntrs(t *testing.T) {
	tests.StaticSetInterfaceValPntrs(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceContainsPntr(t *testing.T) {
	tests.StaticSetInterfaceContainsPntr(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceGetUnique(t *testing.T) {
	tests.StaticSetInterfaceGetUnique(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceContains(t *testing.T) {
	tests.StaticSetInterfaceContains(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceClear(t *testing.T) {
	tests.StaticSetInterfaceClear(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceAppendUnique(t *testing.T) {
	tests.StaticSetInterfaceAppendUnique(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceUpdateUnique(t *testing.T) {
	tests.StaticSetInterfaceUpdateUnique(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfacePop(t *testing.T) {
	tests.StaticSetInterfacePop(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceUnorderedEq(t *testing.T) {
	tests.StaticSetInterfaceUnorderedEq(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceIntersection(t *testing.T) {
	tests.StaticSetInterfaceIntersection(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceUnion(t *testing.T) {
	tests.StaticSetInterfaceUnion(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceDifference(t *testing.T) {
	tests.StaticSetInterfaceDifference(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceIsSuperset(t *testing.T) {
	tests.StaticSetInterfaceIsSuperset(SyncedCircularBufferToSetInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticSetInterfaceIsSubset(t *testing.T) {
	tests.StaticSetInterfaceIsSubset(SyncedCircularBufferToSetInterfaceFactory, t)
}
