package containers

// Code generated by ../../bin/containerInterfaceTests - DO NOT EDIT.
import (
	"github.com/barbell-math/util/src/container/dynamicContainers"
	"github.com/barbell-math/util/src/container/tests"
	"testing"
)

func SyncedVectorToQueueInterfaceFactory(capacity int) dynamicContainers.Queue[int] {
	v := generateSyncedVector(capacity)
	var rv dynamicContainers.Queue[int] = &v
	return rv
}

func TestSyncedVector_DynQueueInterfaceSyncableInterface(t *testing.T) {
	tests.DynQueueInterfaceSyncableInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceAddressableInterface(t *testing.T) {
	tests.DynQueueInterfaceAddressableInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceLengthInterface(t *testing.T) {
	tests.DynQueueInterfaceLengthInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceCapacityInterface(t *testing.T) {
	tests.DynQueueInterfaceCapacityInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceClearInterface(t *testing.T) {
	tests.DynQueueInterfaceClearInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceFirstElemReadInterface(t *testing.T) {
	tests.DynQueueInterfaceFirstElemReadInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceFirstElemDeleteInterface(t *testing.T) {
	tests.DynQueueInterfaceFirstElemDeleteInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceLastElemWriteInterface(t *testing.T) {
	tests.DynQueueInterfaceLastElemWriteInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_ReadDynQueueInterface(t *testing.T) {
	tests.ReadDynQueueInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_WriteDynQueueInterface(t *testing.T) {
	tests.WriteDynQueueInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceInterface(t *testing.T) {
	tests.DynQueueInterfaceInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceStaticCapacityInterface(t *testing.T) {
	tests.DynQueueInterfaceStaticCapacityInterface(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceClear(t *testing.T) {
	tests.DynQueueInterfaceClear(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfacePeekPntrFront(t *testing.T) {
	tests.DynQueueInterfacePeekPntrFront(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfacePeekFront(t *testing.T) {
	tests.DynQueueInterfacePeekFront(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfacePopFront(t *testing.T) {
	tests.DynQueueInterfacePopFront(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfacePushBack(t *testing.T) {
	tests.DynQueueInterfacePushBack(SyncedVectorToQueueInterfaceFactory, t)
}

func TestSyncedVector_DynQueueInterfaceForcePushBack(t *testing.T) {
	tests.DynQueueInterfaceForcePushBack(SyncedVectorToQueueInterfaceFactory, t)
}
