package containers

// Code generated by ../../../bin/containerInterfaceTests - DO NOT EDIT.
import (
	"github.com/barbell-math/util/src/container/dynamicContainers"
	"github.com/barbell-math/util/src/container/tests"
	"testing"
)

func SyncedVectorToDequeInterfaceFactory(capacity int) dynamicContainers.Deque[int] {
	v := generateSyncedVector(capacity)
	var rv dynamicContainers.Deque[int] = &v
	return rv
}

func TestSyncedVector_DynDequeInterfaceSyncableInterface(t *testing.T) {
	tests.DynDequeInterfaceSyncableInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceAddressableInterface(t *testing.T) {
	tests.DynDequeInterfaceAddressableInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceLengthInterface(t *testing.T) {
	tests.DynDequeInterfaceLengthInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceCapacityInterface(t *testing.T) {
	tests.DynDequeInterfaceCapacityInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceClearInterface(t *testing.T) {
	tests.DynDequeInterfaceClearInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceFirstElemReadInterface(t *testing.T) {
	tests.DynDequeInterfaceFirstElemReadInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceFirstElemWriteInterface(t *testing.T) {
	tests.DynDequeInterfaceFirstElemWriteInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceFirstElemDeleteInterface(t *testing.T) {
	tests.DynDequeInterfaceFirstElemDeleteInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceLastElemReadInterface(t *testing.T) {
	tests.DynDequeInterfaceLastElemReadInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceLastElemWriteInterface(t *testing.T) {
	tests.DynDequeInterfaceLastElemWriteInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceLastElemDeleteInterface(t *testing.T) {
	tests.DynDequeInterfaceLastElemDeleteInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_ReadDynDequeInterface(t *testing.T) {
	tests.ReadDynDequeInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_WriteDynDequeInterface(t *testing.T) {
	tests.WriteDynDequeInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceInterface(t *testing.T) {
	tests.DynDequeInterfaceInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceStaticCapacityInterface(t *testing.T) {
	tests.DynDequeInterfaceStaticCapacityInterface(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceClear(t *testing.T) {
	tests.DynDequeInterfaceClear(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfacePeekPntrFront(t *testing.T) {
	tests.DynDequeInterfacePeekPntrFront(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfacePeekFront(t *testing.T) {
	tests.DynDequeInterfacePeekFront(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfacePeekPntrBack(t *testing.T) {
	tests.DynDequeInterfacePeekPntrBack(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfacePeekBack(t *testing.T) {
	tests.DynDequeInterfacePeekBack(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfacePopFront(t *testing.T) {
	tests.DynDequeInterfacePopFront(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfacePopBack(t *testing.T) {
	tests.DynDequeInterfacePopBack(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfacePushFront(t *testing.T) {
	tests.DynDequeInterfacePushFront(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceForcePushFront(t *testing.T) {
	tests.DynDequeInterfaceForcePushFront(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfacePushBack(t *testing.T) {
	tests.DynDequeInterfacePushBack(SyncedVectorToDequeInterfaceFactory, t)
}

func TestSyncedVector_DynDequeInterfaceForcePushBack(t *testing.T) {
	tests.DynDequeInterfaceForcePushBack(SyncedVectorToDequeInterfaceFactory, t)
}
