package containers

// Code generated by ../../../bin/containerInterfaceTests - DO NOT EDIT.
import (
	"github.com/barbell-math/util/src/container/dynamicContainers"
	"github.com/barbell-math/util/src/container/tests"
	"testing"
)

func VectorToDequeInterfaceFactory(capacity int) dynamicContainers.Deque[int] {
	v := generateVector(capacity)
	var rv dynamicContainers.Deque[int] = &v
	return rv
}

func TestVector_DynDequeInterfaceSyncableInterface(t *testing.T) {
	tests.DynDequeInterfaceSyncableInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceAddressableInterface(t *testing.T) {
	tests.DynDequeInterfaceAddressableInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceLengthInterface(t *testing.T) {
	tests.DynDequeInterfaceLengthInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceCapacityInterface(t *testing.T) {
	tests.DynDequeInterfaceCapacityInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceClearInterface(t *testing.T) {
	tests.DynDequeInterfaceClearInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceFirstElemReadInterface(t *testing.T) {
	tests.DynDequeInterfaceFirstElemReadInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceFirstElemWriteInterface(t *testing.T) {
	tests.DynDequeInterfaceFirstElemWriteInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceFirstElemDeleteInterface(t *testing.T) {
	tests.DynDequeInterfaceFirstElemDeleteInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceLastElemReadInterface(t *testing.T) {
	tests.DynDequeInterfaceLastElemReadInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceLastElemWriteInterface(t *testing.T) {
	tests.DynDequeInterfaceLastElemWriteInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceLastElemDeleteInterface(t *testing.T) {
	tests.DynDequeInterfaceLastElemDeleteInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_ReadDynDequeInterface(t *testing.T) {
	tests.ReadDynDequeInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_WriteDynDequeInterface(t *testing.T) {
	tests.WriteDynDequeInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceInterface(t *testing.T) {
	tests.DynDequeInterfaceInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceStaticCapacityInterface(t *testing.T) {
	tests.DynDequeInterfaceStaticCapacityInterface(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceClear(t *testing.T) {
	tests.DynDequeInterfaceClear(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfacePeekPntrFront(t *testing.T) {
	tests.DynDequeInterfacePeekPntrFront(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfacePeekFront(t *testing.T) {
	tests.DynDequeInterfacePeekFront(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfacePeekPntrBack(t *testing.T) {
	tests.DynDequeInterfacePeekPntrBack(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfacePeekBack(t *testing.T) {
	tests.DynDequeInterfacePeekBack(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfacePopFront(t *testing.T) {
	tests.DynDequeInterfacePopFront(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfacePopBack(t *testing.T) {
	tests.DynDequeInterfacePopBack(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfacePushFront(t *testing.T) {
	tests.DynDequeInterfacePushFront(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceForcePushFront(t *testing.T) {
	tests.DynDequeInterfaceForcePushFront(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfacePushBack(t *testing.T) {
	tests.DynDequeInterfacePushBack(VectorToDequeInterfaceFactory, t)
}

func TestVector_DynDequeInterfaceForcePushBack(t *testing.T) {
	tests.DynDequeInterfaceForcePushBack(VectorToDequeInterfaceFactory, t)
}
