package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"math/big"
	"testing"
)

func TestBigFloatValueImplementsTranslator_big_Float_(t *testing.T) {
	var typeThing BigFloat
	var iFaceThing Translator[big.Float] = typeThing
	_ = iFaceThing
}

func TestBigFloatPntrImplementsTranslator_big_Float_(t *testing.T) {
	var typeThing BigFloat
	var iFaceThing Translator[big.Float] = &typeThing
	_ = iFaceThing
}
