package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"math/big"
	"testing"
)

func TestBigIntValueImplementsTranslator_big_Int_(t *testing.T) {
	var typeThing BigInt
	var iFaceThing Translator[big.Int] = typeThing
	_ = iFaceThing
}

func TestBigIntPntrImplementsTranslator_big_Int_(t *testing.T) {
	var typeThing BigInt
	var iFaceThing Translator[big.Int] = &typeThing
	_ = iFaceThing
}
