package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"math/big"
	"testing"
)

func TestBigRatValueImplementsTranslator_big_Rat_(t *testing.T) {
	var typeThing BigRat
	var iFaceThing Translator[big.Rat] = typeThing
	_ = iFaceThing
}

func TestBigRatPntrImplementsTranslator_big_Rat_(t *testing.T) {
	var typeThing BigRat
	var iFaceThing Translator[big.Rat] = &typeThing
	_ = iFaceThing
}
