package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBitsValueImplementsTranslator___byte_(t *testing.T) {
	var typeThing Bits
	var iFaceThing Translator[[]byte] = typeThing
	_ = iFaceThing
}

func TestBitsPntrImplementsTranslator___byte_(t *testing.T) {
	var typeThing Bits
	var iFaceThing Translator[[]byte] = &typeThing
	_ = iFaceThing
}
