package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinInt64ValueImplementsTranslator_int64_(t *testing.T) {
	var typeThing BuiltinInt64
	var iFaceThing Translator[int64] = typeThing
	_ = iFaceThing
}

func TestBuiltinInt64PntrImplementsTranslator_int64_(t *testing.T) {
	var typeThing BuiltinInt64
	var iFaceThing Translator[int64] = &typeThing
	_ = iFaceThing
}
