package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinIntValueImplementsTranslator_int_(t *testing.T) {
	var typeThing BuiltinInt
	var iFaceThing Translator[int] = typeThing
	_ = iFaceThing
}

func TestBuiltinIntPntrImplementsTranslator_int_(t *testing.T) {
	var typeThing BuiltinInt
	var iFaceThing Translator[int] = &typeThing
	_ = iFaceThing
}
