package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinUint8ValueImplementsTranslator_uint8_(t *testing.T) {
	var typeThing BuiltinUint8
	var iFaceThing Translator[uint8] = typeThing
	_ = iFaceThing
}

func TestBuiltinUint8PntrImplementsTranslator_uint8_(t *testing.T) {
	var typeThing BuiltinUint8
	var iFaceThing Translator[uint8] = &typeThing
	_ = iFaceThing
}
