package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinBoolValueImplementsTranslator_bool_(t *testing.T) {
	var typeThing BuiltinBool
	var iFaceThing Translator[bool] = typeThing
	_ = iFaceThing
}

func TestBuiltinBoolPntrImplementsTranslator_bool_(t *testing.T) {
	var typeThing BuiltinBool
	var iFaceThing Translator[bool] = &typeThing
	_ = iFaceThing
}
