package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinInt16ValueImplementsTranslator_int16_(t *testing.T) {
	var typeThing BuiltinInt16
	var iFaceThing Translator[int16] = typeThing
	_ = iFaceThing
}

func TestBuiltinInt16PntrImplementsTranslator_int16_(t *testing.T) {
	var typeThing BuiltinInt16
	var iFaceThing Translator[int16] = &typeThing
	_ = iFaceThing
}
