package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinUint16ValueImplementsTranslator_uint16_(t *testing.T) {
	var typeThing BuiltinUint16
	var iFaceThing Translator[uint16] = typeThing
	_ = iFaceThing
}

func TestBuiltinUint16PntrImplementsTranslator_uint16_(t *testing.T) {
	var typeThing BuiltinUint16
	var iFaceThing Translator[uint16] = &typeThing
	_ = iFaceThing
}
