package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinUint64ValueImplementsTranslator_uint64_(t *testing.T) {
	var typeThing BuiltinUint64
	var iFaceThing Translator[uint64] = typeThing
	_ = iFaceThing
}

func TestBuiltinUint64PntrImplementsTranslator_uint64_(t *testing.T) {
	var typeThing BuiltinUint64
	var iFaceThing Translator[uint64] = &typeThing
	_ = iFaceThing
}
