package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinUint32ValueImplementsTranslator_uint32_(t *testing.T) {
	var typeThing BuiltinUint32
	var iFaceThing Translator[uint32] = typeThing
	_ = iFaceThing
}

func TestBuiltinUint32PntrImplementsTranslator_uint32_(t *testing.T) {
	var typeThing BuiltinUint32
	var iFaceThing Translator[uint32] = &typeThing
	_ = iFaceThing
}
