package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinFloat64ValueImplementsTranslator_float64_(t *testing.T) {
	var typeThing BuiltinFloat64
	var iFaceThing Translator[float64] = typeThing
	_ = iFaceThing
}

func TestBuiltinFloat64PntrImplementsTranslator_float64_(t *testing.T) {
	var typeThing BuiltinFloat64
	var iFaceThing Translator[float64] = &typeThing
	_ = iFaceThing
}
