package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinInt8ValueImplementsTranslator_int8_(t *testing.T) {
	var typeThing BuiltinInt8
	var iFaceThing Translator[int8] = typeThing
	_ = iFaceThing
}

func TestBuiltinInt8PntrImplementsTranslator_int8_(t *testing.T) {
	var typeThing BuiltinInt8
	var iFaceThing Translator[int8] = &typeThing
	_ = iFaceThing
}
