package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinComplex64ValueImplementsTranslator_complex64_(t *testing.T) {
	var typeThing BuiltinComplex64
	var iFaceThing Translator[complex64] = typeThing
	_ = iFaceThing
}

func TestBuiltinComplex64PntrImplementsTranslator_complex64_(t *testing.T) {
	var typeThing BuiltinComplex64
	var iFaceThing Translator[complex64] = &typeThing
	_ = iFaceThing
}
