package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestBuiltinInt32ValueImplementsTranslator_int32_(t *testing.T) {
	var typeThing BuiltinInt32
	var iFaceThing Translator[int32] = typeThing
	_ = iFaceThing
}

func TestBuiltinInt32PntrImplementsTranslator_int32_(t *testing.T) {
	var typeThing BuiltinInt32
	var iFaceThing Translator[int32] = &typeThing
	_ = iFaceThing
}
