package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestCIDRTranslatorValueImplementsTranslator_CIDRVals_(t *testing.T) {
	var typeThing CIDRTranslator
	var iFaceThing Translator[CIDRVals] = typeThing
	_ = iFaceThing
}

func TestCIDRTranslatorPntrImplementsTranslator_CIDRVals_(t *testing.T) {
	var typeThing CIDRTranslator
	var iFaceThing Translator[CIDRVals] = &typeThing
	_ = iFaceThing
}
