package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestDirValueImplementsTranslator_string_(t *testing.T) {
	var typeThing Dir
	var iFaceThing Translator[string] = typeThing
	_ = iFaceThing
}

func TestDirPntrImplementsTranslator_string_(t *testing.T) {
	var typeThing Dir
	var iFaceThing Translator[string] = &typeThing
	_ = iFaceThing
}
