package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
	stdTime "time"
)

func TestDurationValueImplementsTranslator_stdTime_Duration_(t *testing.T) {
	var typeThing Duration
	var iFaceThing Translator[stdTime.Duration] = typeThing
	_ = iFaceThing
}

func TestDurationPntrImplementsTranslator_stdTime_Duration_(t *testing.T) {
	var typeThing Duration
	var iFaceThing Translator[stdTime.Duration] = &typeThing
	_ = iFaceThing
}
