package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	testenum "github.com/barbell-math/util/src/argparse/testEnum"
	"testing"
)

func TestEnumValueImplementsTranslator_testenum_TestEnum_(t *testing.T) {
	var typeThing Enum[*testenum.TestEnum, testenum.TestEnum]
	var iFaceThing Translator[testenum.TestEnum] = typeThing
	_ = iFaceThing
}

func TestEnumPntrImplementsTranslator_testenum_TestEnum_(t *testing.T) {
	var typeThing Enum[*testenum.TestEnum, testenum.TestEnum]
	var iFaceThing Translator[testenum.TestEnum] = &typeThing
	_ = iFaceThing
}
