package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestEnvVarValueImplementsTranslator_string_(t *testing.T) {
	var typeThing EnvVar
	var iFaceThing Translator[string] = typeThing
	_ = iFaceThing
}

func TestEnvVarPntrImplementsTranslator_string_(t *testing.T) {
	var typeThing EnvVar
	var iFaceThing Translator[string] = &typeThing
	_ = iFaceThing
}
