package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestFileValueImplementsTranslator_string_(t *testing.T) {
	var typeThing File
	var iFaceThing Translator[string] = typeThing
	_ = iFaceThing
}

func TestFilePntrImplementsTranslator_string_(t *testing.T) {
	var typeThing File
	var iFaceThing Translator[string] = &typeThing
	_ = iFaceThing
}
