package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestFlagCntrPntrImplementsTranslator_int_(t *testing.T) {
	var typeThing FlagCntr[int]
	var iFaceThing Translator[int] = &typeThing
	_ = iFaceThing
}
