package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestFlagValueImplementsTranslator_bool_(t *testing.T) {
	var typeThing Flag
	var iFaceThing Translator[bool] = typeThing
	_ = iFaceThing
}

func TestFlagPntrImplementsTranslator_bool_(t *testing.T) {
	var typeThing Flag
	var iFaceThing Translator[bool] = &typeThing
	_ = iFaceThing
}
