package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"github.com/barbell-math/util/src/widgets"
	"testing"
)

func TestListValuesPntrImplementsTranslator___bool_(t *testing.T) {
	var typeThing ListValues[BuiltinBool, widgets.BuiltinBool, bool]
	var iFaceThing Translator[[]bool] = &typeThing
	_ = iFaceThing
}
