package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"net"
	"testing"
)

func TestMACAddrValueImplementsTranslator_net_HardwareAddr_(t *testing.T) {
	var typeThing MACAddr
	var iFaceThing Translator[net.HardwareAddr] = typeThing
	_ = iFaceThing
}

func TestMACAddrPntrImplementsTranslator_net_HardwareAddr_(t *testing.T) {
	var typeThing MACAddr
	var iFaceThing Translator[net.HardwareAddr] = &typeThing
	_ = iFaceThing
}
