package translators

// Code generated by ../../../bin/structDefaultInit - DO NOT EDIT.
import (
	"io/fs"
)

// Returns a new Mkdir struct initialized with the default values.
func NewMkdir() Mkdir {
	return Mkdir{
		permissions: 0644,
	}
}

// The permissions used to create all dirs and sub-dirs. See
// [os.MkdirAll] for reference.
//
//gen:structDefaultInit default 0644
//gen:structDefaultInit setter
//gen:structDefaultInit getter
//gen:structDefaultInit imports io/fs
func (o *Mkdir) SetPermissions(v fs.FileMode) *Mkdir {
	o.permissions = v
	return o
}

// The permissions used to create all dirs and sub-dirs. See
// [os.MkdirAll] for reference.
//
//gen:structDefaultInit default 0644
//gen:structDefaultInit setter
//gen:structDefaultInit getter
//gen:structDefaultInit imports io/fs
func (o *Mkdir) GetPermissions() fs.FileMode {
	return o.permissions
}
