package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestMkdirValueImplementsTranslator_string_(t *testing.T) {
	var typeThing Mkdir
	var iFaceThing Translator[string] = typeThing
	_ = iFaceThing
}

func TestMkdirPntrImplementsTranslator_string_(t *testing.T) {
	var typeThing Mkdir
	var iFaceThing Translator[string] = &typeThing
	_ = iFaceThing
}
