package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestNoopValueImplementsTranslator_bool_(t *testing.T) {
	var typeThing Noop[bool]
	var iFaceThing Translator[bool] = typeThing
	_ = iFaceThing
}

func TestNoopPntrImplementsTranslator_bool_(t *testing.T) {
	var typeThing Noop[bool]
	var iFaceThing Translator[bool] = &typeThing
	_ = iFaceThing
}
