package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestPortValueImplementsTranslator_uint16_(t *testing.T) {
	var typeThing Port
	var iFaceThing Translator[uint16] = typeThing
	_ = iFaceThing
}

func TestPortPntrImplementsTranslator_uint16_(t *testing.T) {
	var typeThing Port
	var iFaceThing Translator[uint16] = &typeThing
	_ = iFaceThing
}
