package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"net/netip"
	"testing"
)

func TestPrefixValueImplementsTranslator_netip_Prefix_(t *testing.T) {
	var typeThing Prefix
	var iFaceThing Translator[netip.Prefix] = typeThing
	_ = iFaceThing
}

func TestPrefixPntrImplementsTranslator_netip_Prefix_(t *testing.T) {
	var typeThing Prefix
	var iFaceThing Translator[netip.Prefix] = &typeThing
	_ = iFaceThing
}
