package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestRangeValueImplementsTranslator_int_(t *testing.T) {
	var typeThing Range[int, BuiltinInt]
	var iFaceThing Translator[int] = typeThing
	_ = iFaceThing
}

func TestRangePntrImplementsTranslator_int_(t *testing.T) {
	var typeThing Range[int, BuiltinInt]
	var iFaceThing Translator[int] = &typeThing
	_ = iFaceThing
}
