package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestStopperValueImplementsTranslator_bool_(t *testing.T) {
	var typeThing Stopper[bool]
	var iFaceThing Translator[bool] = typeThing
	_ = iFaceThing
}

func TestStopperPntrImplementsTranslator_bool_(t *testing.T) {
	var typeThing Stopper[bool]
	var iFaceThing Translator[bool] = &typeThing
	_ = iFaceThing
}
