package translators

// Code generated by ../../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
	stdTime "time"
)

func TesttimeValueImplementsTranslator_stdTime_Time_(t *testing.T) {
	var typeThing time
	var iFaceThing Translator[stdTime.Time] = typeThing
	_ = iFaceThing
}

func TesttimePntrImplementsTranslator_stdTime_Time_(t *testing.T) {
	var typeThing time
	var iFaceThing Translator[stdTime.Time] = &typeThing
	_ = iFaceThing
}
