package reflect

// Code generated by ../../bin/structDefaultInit - DO NOT EDIT.
import ()

// Returns a new structHashOpts struct initialized with the default values.
func NewStructHashOpts() *structHashOpts {
	return &structHashOpts{
		optionsFlag: NewOptionsFlag(),
	}
}

//gen:structDefaultInit default NewOptionsFlag()
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *structHashOpts) SetOptionsFlag(v optionsFlag) *structHashOpts {
	o.optionsFlag = v
	return o
}

//gen:structDefaultInit default NewOptionsFlag()
//gen:structDefaultInit setter
//gen:structDefaultInit getter
func (o *structHashOpts) GetOptionsFlag() optionsFlag {
	return o.optionsFlag
}
