package containers

// Code generated by ../../bin/containerInterfaceTests - DO NOT EDIT.
import (
	"testing"
	"github.com/barbell-math/util/container/tests"
	"github.com/barbell-math/util/container/staticContainers"
)

func SyncedCircularBufferToQueueInterfaceFactory(capacity int) staticContainers.Queue[int] {
	v := generateSyncedCircularBuffer(capacity)
	var rv staticContainers.Queue[int] = &v
	return rv
}

func TestSyncedCircularBuffer_StaticQueueInterfaceStaticCapacity(t *testing.T) {
	tests.StaticQueueInterfaceStaticCapacity(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfaceLengthInterface(t *testing.T) {
	tests.StaticQueueInterfaceLengthInterface(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfaceCapacityInterface(t *testing.T) {
	tests.StaticQueueInterfaceCapacityInterface(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfaceClearInterface(t *testing.T) {
	tests.StaticQueueInterfaceClearInterface(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfaceFirstElemReadInterface(t *testing.T) {
	tests.StaticQueueInterfaceFirstElemReadInterface(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfaceFirstElemDeleteInterface(t *testing.T) {
	tests.StaticQueueInterfaceFirstElemDeleteInterface(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfaceLastElemWriteInterface(t *testing.T) {
	tests.StaticQueueInterfaceLastElemWriteInterface(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_ReadStaticQueueInterface(t *testing.T) {
	tests.ReadStaticQueueInterface(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_WriteStaticQueueInterface(t *testing.T) {
	tests.WriteStaticQueueInterface(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfaceInterface(t *testing.T) {
	tests.StaticQueueInterfaceInterface(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfaceClear(t *testing.T) {
	tests.StaticQueueInterfaceClear(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfacePeekPntrFront(t *testing.T) {
	tests.StaticQueueInterfacePeekPntrFront(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfacePeekFront(t *testing.T) {
	tests.StaticQueueInterfacePeekFront(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfacePopFront(t *testing.T) {
	tests.StaticQueueInterfacePopFront(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfacePushBack(t *testing.T) {
	tests.StaticQueueInterfacePushBack(SyncedCircularBufferToQueueInterfaceFactory, t)
}

func TestSyncedCircularBuffer_StaticQueueInterfaceForcePushBack(t *testing.T) {
	tests.StaticQueueInterfaceForcePushBack(SyncedCircularBufferToQueueInterfaceFactory, t)
}
