package containers

// Code generated by ../../bin/containerInterfaceTests - DO NOT EDIT.
import (
	"testing"
	"github.com/barbell-math/util/container/tests"
	"github.com/barbell-math/util/container/dynamicContainers"
)

func SyncedHashGraphToDirectedGraphInterfaceFactory(capacity int) dynamicContainers.DirectedGraph[int, int] {
	v := generateSyncedHashGraph(capacity)
	var rv dynamicContainers.DirectedGraph[int, int] = &v
	return rv
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceSyncableInterface(t *testing.T) {
	tests.DynDirectedGraphInterfaceSyncableInterface(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceAddressableInterface(t *testing.T) {
	tests.DynDirectedGraphInterfaceAddressableInterface(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceClearInterface(t *testing.T) {
	tests.DynDirectedGraphInterfaceClearInterface(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_ReadDynDirectedGraphInterface(t *testing.T) {
	tests.ReadDynDirectedGraphInterface(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_WriteDynDirectedGraphInterface(t *testing.T) {
	tests.WriteDynDirectedGraphInterface(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceInterface(t *testing.T) {
	tests.DynDirectedGraphInterfaceInterface(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceStaticCapacityInterface(t *testing.T) {
	tests.DynDirectedGraphInterfaceStaticCapacityInterface(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceContainsEdge(t *testing.T) {
	tests.DynDirectedGraphInterfaceContainsEdge(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceContainsEdgePntr(t *testing.T) {
	tests.DynDirectedGraphInterfaceContainsEdgePntr(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceContainsVertex(t *testing.T) {
	tests.DynDirectedGraphInterfaceContainsVertex(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceContainsVertexPntr(t *testing.T) {
	tests.DynDirectedGraphInterfaceContainsVertexPntr(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceEdges(t *testing.T) {
	tests.DynDirectedGraphInterfaceEdges(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceEdgePntrs(t *testing.T) {
	tests.DynDirectedGraphInterfaceEdgePntrs(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceVertices(t *testing.T) {
	tests.DynDirectedGraphInterfaceVertices(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphInterfaceVerticePntrs(t *testing.T) {
	tests.DynDirectedGraphInterfaceVerticePntrs(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphLink(t *testing.T) {
	tests.DynDirectedGraphLink(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphLinkPntr(t *testing.T) {
	tests.DynDirectedGraphLinkPntr(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphNumOutLinks(t *testing.T) {
	tests.DynDirectedGraphNumOutLinks(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphNumOutLinksPntr(t *testing.T) {
	tests.DynDirectedGraphNumOutLinksPntr(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphOutEdges(t *testing.T) {
	tests.DynDirectedGraphOutEdges(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphOutEdgePntrs(t *testing.T) {
	tests.DynDirectedGraphOutEdgePntrs(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphOutVertices(t *testing.T) {
	tests.DynDirectedGraphOutVertices(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphOutVerticePntrs(t *testing.T) {
	tests.DynDirectedGraphOutVerticePntrs(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphOutEdgesAndVertices(t *testing.T) {
	tests.DynDirectedGraphOutEdgesAndVertices(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphOutEdgesAndVerticePntrs(t *testing.T) {
	tests.DynDirectedGraphOutEdgesAndVerticePntrs(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphEdgesBetween(t *testing.T) {
	tests.DynDirectedGraphEdgesBetween(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphEdgesBetweenPntr(t *testing.T) {
	tests.DynDirectedGraphEdgesBetweenPntr(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphDeleteLink(t *testing.T) {
	tests.DynDirectedGraphDeleteLink(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphDeleteLinkPntr(t *testing.T) {
	tests.DynDirectedGraphDeleteLinkPntr(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphDeleteLinks(t *testing.T) {
	tests.DynDirectedGraphDeleteLinks(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphDeleteLinksPntr(t *testing.T) {
	tests.DynDirectedGraphDeleteLinksPntr(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphDeleteVertex(t *testing.T) {
	tests.DynDirectedGraphDeleteVertex(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphDeleteVertexPntr(t *testing.T) {
	tests.DynDirectedGraphDeleteVertexPntr(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphDeleteEdge(t *testing.T) {
	tests.DynDirectedGraphDeleteEdge(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphDeleteEdgePntr(t *testing.T) {
	tests.DynDirectedGraphDeleteEdgePntr(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphClear(t *testing.T) {
	tests.DynDirectedGraphClear(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphKeyedEq(t *testing.T) {
	tests.DynDirectedGraphKeyedEq(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphIntersection(t *testing.T) {
	tests.DynDirectedGraphIntersection(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphUnion(t *testing.T) {
	tests.DynDirectedGraphUnion(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphDifference(t *testing.T) {
	tests.DynDirectedGraphDifference(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphIsSuperset(t *testing.T) {
	tests.DynDirectedGraphIsSuperset(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}

func TestSyncedHashGraph_DynDirectedGraphIsSubset(t *testing.T) {
	tests.DynDirectedGraphIsSubset(SyncedHashGraphToDirectedGraphInterfaceFactory, t)
}
