package containers

// Code generated by ../../bin/containerInterfaceTests - DO NOT EDIT.
import (
	"github.com/barbell-math/util/container/dynamicContainers"
	"github.com/barbell-math/util/container/tests"
	"testing"
)

func VectorToStackInterfaceFactory(capacity int) dynamicContainers.Stack[int] {
	v := generateVector(capacity)
	var rv dynamicContainers.Stack[int] = &v
	return rv
}

func TestVector_DynStackInterfaceSyncableInterface(t *testing.T) {
	tests.DynStackInterfaceSyncableInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceAddressableInterface(t *testing.T) {
	tests.DynStackInterfaceAddressableInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceLengthInterface(t *testing.T) {
	tests.DynStackInterfaceLengthInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceCapacityInterface(t *testing.T) {
	tests.DynStackInterfaceCapacityInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceClearInterface(t *testing.T) {
	tests.DynStackInterfaceClearInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceLastElemReadInterface(t *testing.T) {
	tests.DynStackInterfaceLastElemReadInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceLastElemWriteInterface(t *testing.T) {
	tests.DynStackInterfaceLastElemWriteInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceLastElemDeleteInterface(t *testing.T) {
	tests.DynStackInterfaceLastElemDeleteInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_ReadDynStackInterface(t *testing.T) {
	tests.ReadDynStackInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_WriteDynStackInterface(t *testing.T) {
	tests.WriteDynStackInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceInterface(t *testing.T) {
	tests.DynStackInterfaceInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceStaticCapacityInterface(t *testing.T) {
	tests.DynStackInterfaceStaticCapacityInterface(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceClear(t *testing.T) {
	tests.DynStackInterfaceClear(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfacePeekPntrBack(t *testing.T) {
	tests.DynStackInterfacePeekPntrBack(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfacePeekBack(t *testing.T) {
	tests.DynStackInterfacePeekBack(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfacePopBack(t *testing.T) {
	tests.DynStackInterfacePopBack(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfacePushBack(t *testing.T) {
	tests.DynStackInterfacePushBack(VectorToStackInterfaceFactory, t)
}

func TestVector_DynStackInterfaceForcePushBack(t *testing.T) {
	tests.DynStackInterfaceForcePushBack(VectorToStackInterfaceFactory, t)
}
