package widgets

// Code generated by ../../bin/widgetInterfaceImpl - DO NOT EDIT.

import (
	"github.com/barbell-math/util/src/hash"

	"hash/maphash"
)

var (
	// The random seed will be different every time the program runs
	// meaning that between runs the hash values will not be consistent.
	// This was done for security purposes.
	RANDOM_SEED_STRING maphash.Seed = maphash.MakeSeed()
)

// A widget to represent the built-in string type
type (
	BuiltinString struct{}
)

// Returns true if both string's are equal. Uses the standard == operator internally.
func (_ BuiltinString) Eq(l *string, r *string) bool {
	return *l == *r
}

// Provides a hash function for the value that it is wrapping.
func (_ BuiltinString) Hash(v *string) hash.Hash {
	return hash.Hash(maphash.String(RANDOM_SEED_STRING, *(v)))
}

// Zeros the supplied value.
func (_ BuiltinString) Zero(other *string) {
	*other = (string)("")
}

// Returns true if l<r. Uses the standard < operator internally.
func (_ BuiltinString) Lt(l *string, r *string) bool {
	return *l < *r
}
