package widgets

// Code generated by ../../bin/widgetInterfaceImpl - DO NOT EDIT.

import (
	"github.com/barbell-math/util/src/hash"
)

var ()

// A widget to represent the built-in uint8 type
type (
	BuiltinUint8 struct{}
)

// Returns true if both uint8's are equal. Uses the standard == operator internally.
func (_ BuiltinUint8) Eq(l *uint8, r *uint8) bool {
	return *l == *r
}

// Provides a hash function for the value that it is wrapping.
func (_ BuiltinUint8) Hash(v *uint8) hash.Hash {
	return hash.Hash(*v)
}

// Zeros the supplied value.
func (_ BuiltinUint8) Zero(other *uint8) {
	*other = (uint8)(0)
}

// Returns true if l<r. Uses the standard < operator internally.
func (_ BuiltinUint8) Lt(l *uint8, r *uint8) bool {
	return *l < *r
}

// Returns the zero value for the uint8 type.
func (_ BuiltinUint8) ZeroVal() uint8 {
	return uint8(0)
}

// Returns the unit value for the uint8 type.
func (_ BuiltinUint8) UnitVal() uint8 {
	return uint8(1)
}

// Negates v, updating the value that v points to.
func (_ BuiltinUint8) Neg(v *uint8) {
	*v = -(*v)
}

// Adds l to r, placing the result in the value that res points to.
func (_ BuiltinUint8) Add(res *uint8, l *uint8, r *uint8) {
	*res = *l + *r
}

// Subtracts l to r, placing the result in the value that res points to.
func (_ BuiltinUint8) Sub(res *uint8, l *uint8, r *uint8) {
	*res = *l - *r
}

// Multiplies l to r, placing the result in the value that res points to.
func (_ BuiltinUint8) Mul(res *uint8, l *uint8, r *uint8) {
	*res = *l * *r
}

// Divides l to r, placing the result in the value that res points to.
func (_ BuiltinUint8) Div(res *uint8, l *uint8, r *uint8) {
	*res = *l / *r
}
