package widgets

// Code generated by ../bin/widgetInterfaceImpl - DO NOT EDIT.

import (
	"github.com/barbell-math/util/src/hash"
)

var ()

// A widget to represent the built-in int64 type
type (
	BuiltinInt64 struct{}
)

// Returns true if both int64's are equal. Uses the standard == operator internally.
func (_ BuiltinInt64) Eq(l *int64, r *int64) bool {
	return *l == *r
}

// Provides a hash function for the value that it is wrapping.
func (_ BuiltinInt64) Hash(v *int64) hash.Hash {
	return hash.Hash(*v)
}

// Zeros the supplied value.
func (_ BuiltinInt64) Zero(other *int64) {
	*other = (int64)(0)
}

// Returns true if l<r. Uses the standard < operator internally.
func (_ BuiltinInt64) Lt(l *int64, r *int64) bool {
	return *l < *r
}

// Returns the zero value for the int64 type.
func (_ BuiltinInt64) ZeroVal() int64 {
	return int64(0)
}

// Returns the unit value for the int64 type.
func (_ BuiltinInt64) UnitVal() int64 {
	return int64(1)
}

// Negates v, updating the value that v points to.
func (_ BuiltinInt64) Neg(v *int64) {
	*v = -(*v)
}

// Adds l to r, placing the result in the value that res points to.
func (_ BuiltinInt64) Add(res *int64, l *int64, r *int64) {
	*res = *l + *r
}

// Subtracts l to r, placing the result in the value that res points to.
func (_ BuiltinInt64) Sub(res *int64, l *int64, r *int64) {
	*res = *l - *r
}

// Multiplies l to r, placing the result in the value that res points to.
func (_ BuiltinInt64) Mul(res *int64, l *int64, r *int64) {
	*res = *l * *r
}

// Divides l to r, placing the result in the value that res points to.
func (_ BuiltinInt64) Div(res *int64, l *int64, r *int64) {
	*res = *l / *r
}
