package widgets

// Code generated by ../bin/widgetInterfaceImpl - DO NOT EDIT.

import (
	"github.com/barbell-math/util/src/hash"
)

var ()

// A widget to represent the built-in uint type
type (
	BuiltinUint struct{}
)

// Returns true if both uint's are equal. Uses the standard == operator internally.
func (_ BuiltinUint) Eq(l *uint, r *uint) bool {
	return *l == *r
}

// Provides a hash function for the value that it is wrapping.
func (_ BuiltinUint) Hash(v *uint) hash.Hash {
	return hash.Hash(*v)
}

// Zeros the supplied value.
func (_ BuiltinUint) Zero(other *uint) {
	*other = (uint)(0)
}

// Returns true if l<r. Uses the standard < operator internally.
func (_ BuiltinUint) Lt(l *uint, r *uint) bool {
	return *l < *r
}

// Returns the zero value for the uint type.
func (_ BuiltinUint) ZeroVal() uint {
	return uint(0)
}

// Returns the unit value for the uint type.
func (_ BuiltinUint) UnitVal() uint {
	return uint(1)
}

// Negates v, updating the value that v points to.
func (_ BuiltinUint) Neg(v *uint) {
	*v = -(*v)
}

// Adds l to r, placing the result in the value that res points to.
func (_ BuiltinUint) Add(res *uint, l *uint, r *uint) {
	*res = *l + *r
}

// Subtracts l to r, placing the result in the value that res points to.
func (_ BuiltinUint) Sub(res *uint, l *uint, r *uint) {
	*res = *l - *r
}

// Multiplies l to r, placing the result in the value that res points to.
func (_ BuiltinUint) Mul(res *uint, l *uint, r *uint) {
	*res = *l * *r
}

// Divides l to r, placing the result in the value that res points to.
func (_ BuiltinUint) Div(res *uint, l *uint, r *uint) {
	*res = *l / *r
}
