package generatortests

// Code generated by ../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestTestStructBothImplsIFaceValueImplementsIFace(t *testing.T) {
	var typeThing TestStructBothImplsIFace
	var iFaceThing IFace = typeThing
	_ = iFaceThing
}

func TestTestStructBothImplsIFacePntrImplementsIFace(t *testing.T) {
	var typeThing TestStructBothImplsIFace
	var iFaceThing IFace = &typeThing
	_ = iFaceThing
}
