package generatortests

// Code generated by ../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestTestStructPntrImplsIFacePntrImplementsIFace(t *testing.T) {
	var typeThing TestStructPntrImplsIFace
	var iFaceThing IFace = &typeThing
	_ = iFaceThing
}
