package generatortests

// Code generated by ../../bin/ifaceImplCheck - DO NOT EDIT.
import (
	"testing"
)

func TestTestIntPntrImplsIFacePntrImplementsIFace(t *testing.T) {
	var typeThing TestIntPntrImplsIFace
	var iFaceThing IFace = &typeThing
	_ = iFaceThing
}
