# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Unit Tests

on:
  push:
    branches: [ "main", "refactor" ]
  pull_request:

jobs:

  buildAndTest:
    name: Test on Go v${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.21', '1.22']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go v${{ matrix.go_version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Generate
      run: go generate -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
